name: Test OSV scan against Debian 11

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  scan-debian-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Pull Debian 11 image
        run: |
          docker pull debian:11
          docker image ls debian:11

      - name: Save Debian image to tar (for safe offline scan)
        run: |
          docker save debian:11 -o debian11.tar
          ls -lh debian11.tar

      - name: Download osv-scanner binary
        run: |
          # use prebuilt binary from google/osv-scanner releases
          wget -qO /usr/local/bin/osv-scanner \
            https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64
          chmod +x /usr/local/bin/osv-scanner
          osv-scanner --version

      - name: Scan the saved Debian image with osv-scanner
        run: |
          # Scans the exported image archive (no container code executed during analysis)
          /usr/local/bin/osv-scanner scan image --archive ./debian11.tar --format table --output findings.txt || true
          echo "===== Findings (first 200 lines) ====="
          head -n 200 findings.txt || true

      - name: Upload findings (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: osv-findings-debian11
          path: findings.txt
